---
- hosts: all
  vars:
    dbname: apollo_db
    dbuser: apollo_pg
    dbpassword: apollo_db_password
    dblisten_addresses:
      - "{{ hostvars[inventory_hostname]['ansible_all_ipv4_addresses'][1] }}"
      - localhost
    use_ssl: False
    db_backup_dir: ~/apollo_db_backups/
  roles:
    - base
    - database
    - haproxy
    - vagrant
