#!/usr/bin/env python

version_file_path = "./VERSION"
file = open(version_file_path, "r")
major = 0
minor = 5
current_version = file.read()
current = current_version.split(".")
revision = 0

if(int(current[0]) == major and int(current[1]) == minor):
    revision = int(current[2])+1

file = open(version_file_path,"w")

new_version = "{0}.{1}.{2}".format(major, minor, revision)

file.write("{0}.{1}.{2}\n".format(major, minor, revision))

print new_version
