#!/bin/bash
set -e

PROJECT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

TARGET_DIR=/opt/apollocli
TARGET_SCRIPT=/usr/local/bin/apollo
PUBLISH_DIR=clipublish

if [ -d "$PUBLISH_DIR" ]; then
    rm -rf "$PUBLISH_DIR"
fi

pushd server/Apollo.CLI
dotnet restore
dotnet publish -c Release -o ../../clipublish
popd

sudo rm -rf "$TARGET_DIR"
sudo cp -r "$PUBLISH_DIR" "$TARGET_DIR"
sudo cp prod_cli "$TARGET_SCRIPT"
sudo chmod +x "$TARGET_SCRIPT"
