#!/bin/bash
set -e

PROJECT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
APOLLO_CONSOLE_EXE=$PROJECT_DIR/Apollo.CLI/bin/Debug/netcoreapp1.1/Apollo.CLI.dll

APOLLO_CONSOLE_MODE="dev"

pushd Apollo.CLI
dotnet clean
dotnet restore
dotnet build
popd

export APOLLO_CONSOLE_MODE
dotnet "$APOLLO_CONSOLE_EXE" "$@"
