#!/bin/bash
set -e

APOLLO_EXE=/var/apollo/server/Apollo.exe

# database configuration
APOLLO_DATABASENAME='apollo_db'
APOLLO_DATABASESERVER='127.0.0.1'
APOLLO_DATABASEUSERNAME='apollo_pg'
APOLLO_DATABASEPASSWORD='apollo_db_password'
APOLLO_LOGINHASH='{{ login_hash }}'

export APOLLO_DATABASENAME
export APOLLO_DATABASESERVER
export APOLLO_DATABASEUSERNAME
export APOLLO_DATABASEPASSWORD
export APOLLO_LOGINHASH

mono "$APOLLO_EXE"
