#!/bin/bash
set -e

PROJECT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
APOLLO_CONSOLE_EXE=$PROJECT_DIR/Apollo.CLI/bin/Debug/netcoreapp1.1/Apollo.CLI.dll

APOLLO_CONSOLE_MODE="dev"

if [ ! -f "$APOLLO_CONSOLE_EXE" ]; then
    pushd Apollo.CLI
    dotnet restore
    dotnet build
    popd
fi

export APOLLO_CONSOLE_MODE
dotnet "$APOLLO_CONSOLE_EXE" "$@"
