#!/bin/bash
set -e

PROJECT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
APOLLO_CONSOLE_EXE=$PROJECT_DIR/Apollo.Console/bin/Release/Apollo.Console.exe

APOLLO_CONSOLE_MODE="dev"

if [ ! -f "$APOLLO_CONSOLE_EXE" ]; then
    ./build
fi

export APOLLO_CONSOLE_MODE
mono "$APOLLO_CONSOLE_EXE" "$@"
