#!/bin/bash
set -e

PROJECT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
APOLLO_EXE=$PROJECT_DIR/Apollo/bin/Release/Apollo.exe

# database configuration
APOLLO_DATABASENAME='apollo_db'
APOLLO_DATABASESERVER='127.0.0.1'
APOLLO_DATABASEUSERNAME='apollo_pg'
APOLLO_DATABASEPASSWORD='apollo_db_password'

if [ ! -f "$APOLLO_EXE" ]; then
    ./build
fi

export APOLLO_DATABASENAME
export APOLLO_DATABASESERVER
export APOLLO_DATABASEUSERNAME
export APOLLO_DATABASEPASSWORD

mono "$APOLLO_EXE"
