#!/bin/bash
set -e

# database configuration
APOLLO_DATABASENAME='apollo_db'
APOLLO_DATABASESERVER='127.0.0.1'
APOLLO_DATABASEUSERNAME='apollo_pg'
APOLLO_DATABASEPASSWORD='apollo_db_password'

export APOLLO_DATABASENAME
export APOLLO_DATABASESERVER
export APOLLO_DATABASEUSERNAME
export APOLLO_DATABASEPASSWORD

pushd Apollo
dotnet restore
dotnet run
popd
