#!/bin/bash
set -e

PROJECT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
APOLLO_CONSOLE_DIR=$PROJECT_DIR/Apollo.Console/bin/Release
APOLLO_CONSOLE_EXE=$APOLLO_CONSOLE_DIR/Apollo.Console.exe

TARGET_DIR=/opt/apollocli
TARGET_EXE=$TARGET_DIR/Apollo.Console.exe
TARGET_SCRIPT=/usr/local/bin/apollo

if [ ! -f "$APOLLO_CONSOLE_EXE" ]; then
    ./build
fi

rm -rf "$TARGET_DIR"
cp -r "$APOLLO_CONSOLE_DIR" "$TARGET_DIR"
cp prod_cli "$TARGET_SCRIPT"
