---
- name: Ensure target directory is present
  become: True
  file:
    path: /var/apollo_backups
    state: directory
- name: Copy files to server
  become: yes
  template:
    src: "../templates/{{ item }}"
    dest: "/var/apollo_backups/{{ item }}"
    mode: 0755
  with_items:
    - pg_backup_rotated.sh
    - pg_backup.config
    - pg_backup.sh
- name: Schedule Hourly Backups
  cron:
    name: "backup apollo_db"
    hour: "0-23"
    job: "bash /var/apollo_backups/pg_backup.sh"
    user: "{{ ansible_ssh_user }}"
- name: Schedule Backups Rotation
  cron:
    name: "rotate apollo_db backups"
    minute: 30
    hour: "0-23"
    job: "bash /var/apollo_backups/pg_backup_rotated.sh"
    user: "{{ ansible_ssh_user }}"
