---
- name: Install haproxy
  become: true
  apt:
    name: haproxy
    state: present
- name: Enable haproxy
  become: true
  lineinfile:
    dest: /etc/default/haproxy
    regexp: '^ENABLED='
    line: 'ENABLED=1'
    state: present
  notify:
    - restart haproxy
