---
- name: ensure apt cache is up to date
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 14400
- name: Install apt-get packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - httpie
    - vim
    - python-pip
    - jq
    - build-essential
    - autotools-dev
    - automake
    - apt-transport-https
    - acl
