---
- name: Install Postgres
  become: yes
  apt: name={{item}}
  with_items:
      - postgresql
      - libpq-dev
      - python-psycopg2
- name: Create Database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{dbname}}"
- name: Create Apollo db user
  become: yes
  become_user: postgres
  postgresql_user:
    db: "{{dbname}}"
    name: "{{dbuser}}"
    password: "{{dbpassword}}"
    priv: ALL
- name: Restrict user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{dbuser}}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
- name: Prevent other users from access db
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "{{dbname}}"
    role: PUBLIC
    type: database
    priv: ALL
    state: absent
- name: Install alembic for migrations
  pip:
    name: alembic
    state: present
- name: Configure external ip connections
  become: true
  lineinfile:
    dest: /etc/postgresql/9.5/main/postgresql.conf
    regexp: 'listen_addresses'
    line: "listen_addresses = '{{ dblisten_addresses | join(', ')}}'"
    state: present
  notify:
    - restart postgres
- name: Enable external md5 logins
  become: true
  lineinfile:
    dest: /etc/postgresql/9.5/main/pg_hba.conf
    line: host all all 192.168.0.0/16 md5
    state: present
  notify:
    - restart postgres
- name: Setup password file
  template:
    src: ../templates/pgpass
    dest: ~/.pgpass
    mode: 0600
- include_tasks: backups.yml
