- name: Copy tarball to server
  copy:
    src: ../../../../releases/apollo.latest.tar.gz
    dest: /tmp/apollo.tar.gz
    follow: yes
- name: Ensure target directory is removed
  become: True
  file:
    path: /var/apollo
    state: absent
- name: Decompress build
  become: true
  unarchive:
    src: /tmp/apollo.tar.gz
    dest: /var/
    remote_src: True
- name: Clean up tarball
  file:
    path: /tmp/apollo.tar.gz
    state: absent
- name: Set correct api url in env.js
  lineinfile:
    path: /var/apollo/client/env.js
    regexp: "{{ item.regex }}"
    line:  "{{ item.line }}"
  withItems:
    - regex: '^  API_URL:'
      line: "  API_URL: '{{ apollo_url }}',"
    - regex: '^  BIRTH_DATE:'
      line: "  BIRTH_DATE: {{ birthdate }},"
    - regex: '^  END_DATE:'
      line: "  END_DATE: {{ enddate }},"
