- name: Build and pack locally
  local_action: command ./pack
  args:
    chdir: ../
- name: Copy tarball to server
  copy:
    src: ../apollo.tar.gz
    dest: /tmp/apollo.tar.gz
- name: Ensure target directory is removed
  become: True
  file:
    path: /var/apollo
    state: absent
- name: Decompress build
  become: true
  unarchive:
    src: /tmp/apollo.tar.gz
    dest: /var/
    remote_src: True
- name: Clean up tarball
  file:
    path: /tmp/apollo.tar.gz
    state: absent
- name: Set correct api url in env.js
  lineinfile:
    path: /var/apollo/client/env.js
    regexp: '^  API_URL:'
    line: "  API_URL: '{{ apollo_url }}'"
