---
- name: Copy alembic template over
  become: true
  template:
    src: ../templates/alembic.ini
    dest: /var/apollo/alembic.ini
- name: Run migrations
  command: "/home/{{ ansible_ssh_user }}/.local/bin/alembic upgrade head"
  args:
    chdir: /var/apollo
