---
- name: stop services
  become: true
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - apollo-client
    - apollo-server
- include: build_and_copy.yml
- include: db_migrations.yml
- include: services.yml
