---
- name: stop services
  become: true
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - apollo-client
    - apollo-server
  failed_when: false
- include_tasks: build_and_copy.yml
- include_tasks: db_migrations.yml
- include_tasks: services.yml
