---
- name: Copy scripts over
  template:
    src: "../templates/{{ item }}"
    dest: "/var/apollo/{{ item }}"
    mode: 0744
  with_items:
    - server.sh
- name: Copy unit files over
  become: true
  template:
    src: "../templates/{{ item }}"
    dest: "/etc/systemd/system/apollo-{{ item }}"
    mode: 0744
  with_items:
    - client.service
    - server.service
- name: enable services and ensure started
  become: true
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - apollo-client
    - apollo-server
